#!/usr/bin/env node

/*
* 检查chromium是否正确下载
* 如果已下载，则跳过
* 如果未下载，则执行下载脚本
* */

const chalk = require('chalk');

console.info(`${chalk.blue('Checking Chromium')}...`);

const path = require('path');
const config = require('../config');
const Chromium = require('../chromium');

(async () => {
  if ((await Chromium.isExist) || (await Chromium.isExistLocalCache)) {
    console.info(`${chalk.green('Chromium exist.')}`);
  } else {
    console.info(`${chalk.red('Chromium not exist.')}`);
    console.info(`${chalk.blue('installing Chromium...')}`);
    // run install script
    require(path.join(config.paths.puppeteer, 'install.js'));
  }
})().catch(err => {
  console.error(err);
});
